// SPDX-License-Identifier: MIT
pragma solidity ^0.8.21;

import {Test} from "forge-std/Test.sol";
import {DelegationVerifier} from "../src/DelegationVerifier.sol";

contract DelegationVerifierTest is Test {
    DelegationVerifier public verifier;

    function setUp() public {
        verifier = new DelegationVerifier();
    }

    /// @notice Verify a real UltraHonk proof generated by bb against the
    /// fixtures produced by `cargo run -p infrastructure --bin generate-fixture`.
    function test_verifiesValidDelegationProof() public view {
        bytes memory proof = vm.readFileBinary("test/fixtures/proof.bin");
        bytes memory publicInputsBytes = vm.readFileBinary("test/fixtures/public_inputs.bin");
        require(publicInputsBytes.length % 32 == 0, "public inputs must be a multiple of 32 bytes");

        uint256 numPublicInputs = publicInputsBytes.length / 32;
        bytes32[] memory publicInputs = new bytes32[](numPublicInputs);
        for (uint256 i = 0; i < numPublicInputs; i++) {
            bytes32 value;
            assembly {
                value := mload(add(publicInputsBytes, add(32, mul(i, 32))))
            }
            publicInputs[i] = value;
        }

        bool result = verifier.verify(proof, publicInputs);
        assertTrue(result, "valid delegation proof should verify");
    }

    /// @notice A tampered proof must be rejected (reverts during parsing).
    function test_rejectsTamperedProof() public {
        bytes memory proof = vm.readFileBinary("test/fixtures/proof.bin");
        proof[0] = bytes1(uint8(proof[0]) ^ 0xff);

        bytes memory publicInputsBytes = vm.readFileBinary("test/fixtures/public_inputs.bin");
        uint256 numPublicInputs = publicInputsBytes.length / 32;
        bytes32[] memory publicInputs = new bytes32[](numPublicInputs);
        for (uint256 i = 0; i < numPublicInputs; i++) {
            bytes32 value;
            assembly {
                value := mload(add(publicInputsBytes, add(32, mul(i, 32))))
            }
            publicInputs[i] = value;
        }

        vm.expectRevert();
        verifier.verify(proof, publicInputs);
    }
}
