// SPDX-License-Identifier: MIT
pragma solidity ^0.8.21;

import {Test} from "forge-std/Test.sol";
import {DelegationVerifier} from "../src/DelegationVerifier.sol";
import {DelegationVault} from "../src/DelegationVault.sol";

/// @notice End-to-end integration test that exercises the full on-chain flow
/// with a real Noir/UltraHonk proof generated by `generate-fixture`.
contract DelegationVaultIntegrationTest is Test {
    DelegationVerifier public verifier;
    DelegationVault public vault;

    bytes32 public delegationHash =
        0x91ade02b79eb31565b2b5e9cbf73c2113af09524cc4dac59305b8a9ef7fad9f5;
    uint256 public allowedIntents = 0x05;
    uint256[10] public maxAmounts = [
        uint256(1_000_000),
        2_000_000,
        3_000_000,
        0,
        0,
        0,
        0,
        0,
        0,
        0
    ];
    uint256[5] public allowedProtocols = [uint256(1), 2, 0, 0, 0];
    uint256 public expiry = 4_000_000_000;
    uint256 public nonce = 42;

    function setUp() public {
        verifier = new DelegationVerifier();
        vault = new DelegationVault(verifier);
    }

    function _loadPublicInputs() internal view returns (bytes32[] memory) {
        bytes memory publicInputsBytes = vm.readFileBinary("test/fixtures/public_inputs.bin");
        require(
            publicInputsBytes.length == vault.PUBLIC_INPUTS_SIZE() * 32,
            "fixture size mismatch"
        );

        bytes32[] memory publicInputs = new bytes32[](vault.PUBLIC_INPUTS_SIZE());
        for (uint256 i = 0; i < vault.PUBLIC_INPUTS_SIZE(); i++) {
            bytes32 value;
            assembly {
                value := mload(add(publicInputsBytes, add(32, mul(i, 32))))
            }
            publicInputs[i] = value;
        }
        return publicInputs;
    }

    /// @notice Full flow: user delegates, deposits ETH, agent submits a real
    /// ZK proof, vault executes and decrements the user's balance.
    function test_deposit_delegate_execute_with_real_proof() public {
        bytes memory proof = vm.readFileBinary("test/fixtures/proof.bin");
        bytes32[] memory publicInputs = _loadPublicInputs();

        vm.prank(alice);
        vault.delegate(delegationHash, allowedIntents, maxAmounts, allowedProtocols, expiry, nonce);

        vm.deal(alice, 10 ether);
        vm.prank(alice);
        vault.deposit{value: 10 ether}();

        uint256 amount = 2_000_000;
        vm.prank(agent);
        vault.executeWithProof(proof, publicInputs);

        assertEq(vault.balances(alice), 10 ether - amount);
        assertTrue(vault.usedNonces(delegationHash, nonce));
    }

    address alice = makeAddr("alice");
    address agent = makeAddr("agent");
}
