import { useState } from "react";
import { ShieldCheck, CheckCircle2, Clock, XCircle, ChevronDown, ChevronUp } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Button } from "@/components/ui/button";
import { useProofs } from "@/hooks/useProofs";
import { EmptyState } from "@/components/app/EmptyState";

export function ProofsPage() {
  const { data: proofs, isLoading } = useProofs();
  const [expanded, setExpanded] = useState<Set<string>>(new Set());

  const toggle = (id: string) => {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  return (
    <div className="mx-auto max-w-6xl space-y-6">
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="space-y-2"
      >
        <div>
          <h1 className="font-heading text-3xl font-bold tracking-tight">Proof Explorer</h1>
          <p className="text-muted-foreground">
            Verify zero-knowledge proofs generated by the protocol.
          </p>
        </div>
      </motion.div>

      <Card id="onboarding-proofs-solvency" className="border-emerald-500/20 bg-emerald-500/5">
        <CardHeader className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-emerald-500/10 text-emerald-400">
              <motion.div
                initial={{ scale: 0 }}
                animate={{ scale: 1 }}
                transition={{ type: "spring", stiffness: 200 }}
              >
                <CheckCircle2 className="h-5 w-5" />
              </motion.div>
            </div>
            <div>
              <CardTitle>Vault solvency verified</CardTitle>
              <CardDescription>Last attestation 2 hours ago.</CardDescription>
            </div>
          </div>
          <Badge variant="default" className="w-fit">
            Verified
          </Badge>
        </CardHeader>
      </Card>

      <p id="onboarding-proofs-explanation" className="text-sm text-muted-foreground">
        Each proof is verified on-chain without revealing individual balances.
      </p>

      <Card id="onboarding-proofs-list">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <ShieldCheck className="h-5 w-5 text-accent" />
            Recent proofs
          </CardTitle>
          <CardDescription>Delegation, execution, and solvency proofs.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          {isLoading ? (
            <div className="space-y-3">
              <Skeleton className="h-28 w-full" />
              <Skeleton className="h-28 w-full" />
              <Skeleton className="h-28 w-full" />
            </div>
          ) : proofs?.length === 0 ? (
            <EmptyState
              icon={<ShieldCheck className="h-6 w-6" />}
              title="No proofs yet"
              description="Proofs appear here once intents are executed."
            />
          ) : (
            proofs?.map((proof) => {
              const isExpanded = expanded.has(proof.id);
              return (
                <div key={proof.id} className="rounded-xl border border-border/60 bg-card p-5">
                  <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                    <div className="flex items-center gap-3">
                      <div className="flex h-10 w-10 items-center justify-center rounded-full bg-accent-subtle text-accent">
                        <AnimatePresence mode="wait">
                          {proof.verified ? (
                            <motion.div
                              key="verified"
                              initial={{ pathLength: 0, opacity: 0 }}
                              animate={{ pathLength: 1, opacity: 1 }}
                              transition={{ duration: 0.4 }}
                            >
                              <CheckCircle2 className="h-5 w-5" />
                            </motion.div>
                          ) : (
                            <motion.div key="invalid" initial={{ scale: 0 }} animate={{ scale: 1 }}>
                              <XCircle className="h-5 w-5" />
                            </motion.div>
                          )}
                        </AnimatePresence>
                      </div>
                      <div>
                        <p className="font-heading text-lg font-bold capitalize">
                          {proof.type} Proof
                        </p>
                        <p className="text-sm text-muted-foreground">
                          {proof.verifier} · {proof.constraints} constraints · {proof.proofTime}s
                          generation
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <Badge variant={proof.verified ? "default" : "destructive"}>
                        {proof.verified ? "Verified" : "Invalid"}
                      </Badge>
                      <Button variant="ghost" size="sm" onClick={() => toggle(proof.id)}>
                        {isExpanded ? (
                          <ChevronUp className="h-4 w-4" />
                        ) : (
                          <ChevronDown className="h-4 w-4" />
                        )}
                      </Button>
                    </div>
                  </div>
                  <AnimatePresence>
                    {isExpanded && (
                      <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: "auto", opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        className="overflow-hidden"
                      >
                        <div className="mt-4 rounded-lg border border-border/60 bg-secondary p-4 text-xs text-muted-foreground">
                          <p>
                            <strong>Verifier:</strong> {proof.verifier}
                          </p>
                          <p className="mt-1">
                            <strong>Constraints:</strong> {proof.constraints.toLocaleString()}
                          </p>
                          <p className="mt-1">
                            <strong>Proof generation time:</strong> {proof.proofTime}s
                          </p>
                          {proof.txHash && (
                            <p className="mt-1">
                              <strong>Tx hash:</strong> {proof.txHash}
                            </p>
                          )}
                          <p className="mt-1 flex items-center gap-1">
                            <Clock className="h-3 w-3" />
                            {new Date(proof.timestamp).toLocaleString()}
                          </p>
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              );
            })
          )}
        </CardContent>
      </Card>
    </div>
  );
}
